
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile  
    platform: linux/amd64           
    volumes:
      - ./Backend:/app
      - ./Backend/data:/app/data
    ports:
      - "8080:3001"
    environment:
      - PORT=3001

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile         
    platform: linux/amd64
    volumes:
      - ./Frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend